import { SignIn, SignInButton, SignOutButton, useUser } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { api } from '~/utils/api';
import type { RouterOutputs } from '~/utils/api';

import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { LoadingPage, LoadingSpinner } from '~/components/loading';
import { useState } from 'react';
import toast from 'react-hot-toast';


const SinglePostPage: NextPage = () => {
	
	return (
		<>
			<Head>
				<title>Chirp - Emoiji Messenger</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen justify-center">
				<div>Profile View</div>
			</main>
		</>
	);
};

export default SinglePostPage;
