import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  const user = useUser();

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#fff] to-[#0019f7]">
        <div>{user.isSignedIn ? <SignOutButton /> : <SignInButton />}</div>
        <div>
          {data?.map(post => (<div key={post.id}>{post.content}</div>))}
        </div>
      </main>
    </>
  );
};

export default Home;
